[2025-02-14T15:03:04.357-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T15:03:04.376-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-02-14T19:59:27.336193+00:00 [queued]>
[2025-02-14T15:03:04.385-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-02-14T19:59:27.336193+00:00 [queued]>
[2025-02-14T15:03:04.387-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-02-14T15:03:04.401-0500] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): etl_ex_bbva> on 2025-02-14 19:59:27.336193+00:00
[2025-02-14T15:03:04.408-0500] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=67963) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T15:03:04.409-0500] {standard_task_runner.py:72} INFO - Started process 67965 to run task
[2025-02-14T15:03:04.411-0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'etl_ex_bbva', 'manual__2025-02-14T19:59:27.336193+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmpxqoghhu6']
[2025-02-14T15:03:04.412-0500] {standard_task_runner.py:105} INFO - Job 135: Subtask etl_ex_bbva
[2025-02-14T15:03:04.467-0500] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-02-14T19:59:27.336193+00:00 [running]> on host 21f1c1b48730
[2025-02-14T15:03:04.561-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='etl_ex_bbva' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T19:59:27.336193+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T19:59:27.336193+00:00'
[2025-02-14T15:03:04.562-0500] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T15:03:04.579-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-14T15:03:04.580-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/etl_ex_bbva.py']
[2025-02-14T15:03:04.590-0500] {subprocess.py:99} INFO - Output:
[2025-02-14T15:03:07.189-0500] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-02-14T15:03:07.191-0500] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-02-14T15:03:07.192-0500] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-02-14T15:03:07.193-0500] {subprocess.py:106} INFO -              'port': '3306',
[2025-02-14T15:03:07.194-0500] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-02-14T15:03:07.230-0500] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-02-14T15:03:07.231-0500] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-02-14T15:03:07.232-0500] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-02-14T15:03:07.233-0500] {subprocess.py:106} INFO -              'port': '3306',
[2025-02-14T15:03:07.239-0500] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-02-14T15:03:07.888-0500] {subprocess.py:106} INFO - 2025-02-14 15:03:07,887 - assets - INFO - Engine para base de datos: calidad_etl creado exitosamente
[2025-02-14T15:03:07.892-0500] {subprocess.py:106} INFO - ic| hoy: datetime.date(2025, 2, 14)
[2025-02-14T15:03:07.893-0500] {subprocess.py:106} INFO -     fecha_inicio: datetime.date(2025, 2, 1)
[2025-02-14T15:03:07.896-0500] {subprocess.py:106} INFO - ic| fecha_inicio: datetime.date(2025, 2, 1)
[2025-02-14T15:03:07.897-0500] {subprocess.py:106} INFO -     fecha_fin: datetime.date(2025, 2, 14)
[2025-02-14T15:03:07.900-0500] {subprocess.py:106} INFO - ic| query: '
[2025-02-14T15:03:07.900-0500] {subprocess.py:106} INFO -             SELECT * FROM calidad_etl.sm_cerrado
[2025-02-14T15:03:07.901-0500] {subprocess.py:106} INFO -                 WHERE "INSERTAR_DT" >= %s;
[2025-02-14T15:03:07.901-0500] {subprocess.py:106} INFO -             '
[2025-02-14T15:03:08.407-0500] {subprocess.py:106} INFO - 2025-02-14 15:03:08,407 - assets - INFO - SQL query succesfully executed
[2025-02-14T15:03:08.408-0500] {subprocess.py:106} INFO - 2025-02-14 15:03:08,407 - etl_ex_bbva - INFO - Start ETL Exito Tuya BBVA
[2025-02-14T15:03:59.340-0500] {subprocess.py:106} INFO - 2025-02-14 15:03:59,339 - etl_ex_bbva - INFO - Reporte como_vamos.xlsx successfully load
[2025-02-14T15:04:01.457-0500] {subprocess.py:106} INFO - 2025-02-14 15:04:01,457 - etl_ex_bbva - INFO - etl_ex_bbva.py success execution
[2025-02-14T15:04:01.458-0500] {subprocess.py:106} INFO - Conexi√≥n exitosa a la base de datos: calidad_etl
[2025-02-14T15:04:01.783-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-14T15:04:01.812-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T15:04:01.813-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=etl_ex_bbva, run_id=manual__2025-02-14T19:59:27.336193+00:00, execution_date=20250214T195927, start_date=20250214T200304, end_date=20250214T200401
[2025-02-14T15:04:01.837-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T15:04:01.859-0500] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-14T15:04:01.863-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
