[2025-02-01T00:17:46.514-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T00:17:46.559-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-02-01T05:11:44.390818+00:00 [queued]>
[2025-02-01T00:17:46.583-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-02-01T05:11:44.390818+00:00 [queued]>
[2025-02-01T00:17:46.584-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-01T00:17:46.621-0500] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): etl_ex_bbva> on 2025-02-01 05:11:44.390818+00:00
[2025-02-01T00:17:46.636-0500] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=393) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-01T00:17:46.640-0500] {standard_task_runner.py:72} INFO - Started process 394 to run task
[2025-02-01T00:17:46.640-0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'etl_ex_bbva', 'manual__2025-02-01T05:11:44.390818+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmplnsfdgos']
[2025-02-01T00:17:46.643-0500] {standard_task_runner.py:105} INFO - Job 84: Subtask etl_ex_bbva
[2025-02-01T00:17:46.764-0500] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-02-01T05:11:44.390818+00:00 [running]> on host d596638090b4
[2025-02-01T00:17:46.978-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='etl_ex_bbva' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T05:11:44.390818+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T05:11:44.390818+00:00'
[2025-02-01T00:17:46.980-0500] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T00:17:47.022-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-01T00:17:47.025-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/etl_ex_bbva.py']
[2025-02-01T00:17:47.050-0500] {subprocess.py:99} INFO - Output:
[2025-02-01T00:17:53.023-0500] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-02-01T00:17:53.024-0500] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-02-01T00:17:53.026-0500] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-02-01T00:17:53.027-0500] {subprocess.py:106} INFO -              'port': '3306',
[2025-02-01T00:17:53.029-0500] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-02-01T00:17:53.106-0500] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-02-01T00:17:53.108-0500] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-02-01T00:17:53.110-0500] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-02-01T00:17:53.113-0500] {subprocess.py:106} INFO -              'port': '3306',
[2025-02-01T00:17:53.115-0500] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-02-01T00:17:53.409-0500] {subprocess.py:106} INFO - 2025-02-01 00:17:53,408 - assets - INFO - Engine para base de datos: calidad_etl creado exitosamente
[2025-02-01T00:17:53.417-0500] {subprocess.py:106} INFO - ic| hoy: datetime.date(2025, 2, 1)
[2025-02-01T00:17:53.419-0500] {subprocess.py:106} INFO -     fecha_inicio: datetime.date(2025, 2, 1)
[2025-02-01T00:17:53.426-0500] {subprocess.py:106} INFO - ic| fecha_inicio: datetime.date(2025, 2, 1)
[2025-02-01T00:17:53.428-0500] {subprocess.py:106} INFO -     fecha_fin: datetime.date(2025, 2, 1)
[2025-02-01T00:17:53.434-0500] {subprocess.py:106} INFO - ic| query: '
[2025-02-01T00:17:53.436-0500] {subprocess.py:106} INFO -             SELECT * FROM calidad_etl.sm_cerrado
[2025-02-01T00:17:53.438-0500] {subprocess.py:106} INFO -                 WHERE "INSERTAR_DT" >= %s;
[2025-02-01T00:17:53.440-0500] {subprocess.py:106} INFO -             '
[2025-02-01T00:17:54.148-0500] {subprocess.py:106} INFO - 2025-02-01 00:17:54,147 - assets - INFO - SQL query succesfully executed
[2025-02-01T00:17:54.155-0500] {subprocess.py:106} INFO - 2025-02-01 00:17:54,150 - etl_ex_bbva - INFO - Start ETL Exito Tuya BBVA
[2025-02-01T00:22:32.503-0500] {subprocess.py:106} INFO - 2025-02-01 00:22:32,502 - etl_ex_bbva - INFO - Reporte como_vamos.xlsx successfully load
[2025-02-01T00:22:45.214-0500] {subprocess.py:106} INFO - 2025-02-01 00:22:45,213 - etl_ex_bbva - INFO - etl_ex_bbva.py success execution
[2025-02-01T00:22:45.217-0500] {subprocess.py:106} INFO - Conexi√≥n exitosa a la base de datos: calidad_etl
[2025-02-01T00:22:45.997-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-01T00:22:46.076-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T00:22:46.078-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=etl_ex_bbva, run_id=manual__2025-02-01T05:11:44.390818+00:00, execution_date=20250201T051144, start_date=20250201T051746, end_date=20250201T052246
[2025-02-01T00:22:46.129-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T00:22:46.198-0500] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-01T00:22:46.203-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
