[2025-02-12T06:30:01.125-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T06:30:01.151-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos scheduled__2025-02-11T11:30:00+00:00 [queued]>
[2025-02-12T06:30:01.163-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos scheduled__2025-02-11T11:30:00+00:00 [queued]>
[2025-02-12T06:30:01.164-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-02-12T06:30:01.187-0500] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task_bot_como_vamos> on 2025-02-11 11:30:00+00:00
[2025-02-12T06:30:01.194-0500] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=25305) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T06:30:01.196-0500] {standard_task_runner.py:72} INFO - Started process 25306 to run task
[2025-02-12T06:30:01.197-0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'task_bot_como_vamos', 'scheduled__2025-02-11T11:30:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmpy8_t_i0s']
[2025-02-12T06:30:01.199-0500] {standard_task_runner.py:105} INFO - Job 99: Subtask task_bot_como_vamos
[2025-02-12T06:30:01.263-0500] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos scheduled__2025-02-11T11:30:00+00:00 [running]> on host 21f1c1b48730
[2025-02-12T06:30:01.389-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='task_bot_como_vamos' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-11T11:30:00+00:00'
[2025-02-12T06:30:01.391-0500] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T06:30:01.417-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-12T06:30:01.419-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/bot_reporte_como_vamos.py']
[2025-02-12T06:30:01.431-0500] {subprocess.py:99} INFO - Output:
[2025-02-12T06:30:04.990-0500] {subprocess.py:106} INFO - ic| report_date: '11/02/2025'
[2025-02-12T06:30:04.991-0500] {subprocess.py:106} INFO - 2025-02-12 06:30:04,990 - bot_como_vamos - INFO - Starting script bot_como_vamos.py
[2025-02-12T06:30:05.789-0500] {subprocess.py:106} INFO - 2025-02-12 06:30:05,788 - bot_como_vamos - INFO - Conexi√≥n al Selenium Hub establecida correctamente
[2025-02-12T06:31:04.330-0500] {subprocess.py:106} INFO - ic| login_success: <selenium.webdriver.remote.webelement.WebElement (session="91ace4a5d595013a7a5ace4047faf9e9", element="f.550F5463F8318C3B2E0E8B694D235CB6.d.4C97CF31818434BF7F4DF7736A5D7025.e.77")>
[2025-02-12T06:31:04.343-0500] {subprocess.py:106} INFO - 2025-02-12 06:31:04,327 - bot_como_vamos - INFO - Loging success
[2025-02-12T06:31:14.458-0500] {subprocess.py:106} INFO - 2025-02-12 06:31:14,458 - bot_como_vamos - INFO - Click in menu button successfully
[2025-02-12T06:31:24.881-0500] {subprocess.py:106} INFO - 2025-02-12 06:31:24,877 - bot_como_vamos - INFO - Input dates successfully
[2025-02-12T06:31:35.166-0500] {subprocess.py:106} INFO - 2025-02-12 06:31:35,162 - bot_como_vamos - INFO - Click in 'Empresas Y Negocios' successfully
[2025-02-12T06:32:09.054-0500] {subprocess.py:106} INFO - 2025-02-12 06:32:09,053 - assets - INFO - Waiting for download file...............
[2025-02-12T06:32:09.182-0500] {subprocess.py:106} INFO - ic| file: '.com.google.Chrome.1lyA0o'
[2025-02-12T06:32:14.188-0500] {subprocess.py:106} INFO - ic| file: 'Reporte como_vamos.xlsx'
[2025-02-12T06:32:14.189-0500] {subprocess.py:106} INFO - 2025-02-12 06:32:14,188 - bot_como_vamos - INFO - Download Reporte como_vamos succesfully
[2025-02-12T06:32:15.169-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-12T06:32:15.321-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T06:32:15.324-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=task_bot_como_vamos, run_id=scheduled__2025-02-11T11:30:00+00:00, execution_date=20250211T113000, start_date=20250212T113001, end_date=20250212T113215
[2025-02-12T06:32:15.410-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T06:32:15.484-0500] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-02-12T06:32:15.488-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
