[2025-01-31T02:28:48.443+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T02:28:48.483+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-01-31T02:28:45.809531+00:00 [queued]>
[2025-01-31T02:28:48.504+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-01-31T02:28:45.809531+00:00 [queued]>
[2025-01-31T02:28:48.506+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-31T02:28:48.539+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): etl_ex_bbva> on 2025-01-31 02:28:45.809531+00:00
[2025-01-31T02:28:48.553+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=878) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T02:28:48.557+0000] {standard_task_runner.py:72} INFO - Started process 879 to run task
[2025-01-31T02:28:48.558+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'etl_ex_bbva', 'manual__2025-01-31T02:28:45.809531+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmpptsc2i25']
[2025-01-31T02:28:48.560+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask etl_ex_bbva
[2025-01-31T02:28:48.673+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-01-31T02:28:45.809531+00:00 [running]> on host 09b63ee6c6d0
[2025-01-31T02:28:48.951+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='etl_ex_bbva' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T02:28:45.809531+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-31T02:28:45.809531+00:00'
[2025-01-31T02:28:48.953+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T02:28:48.997+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-31T02:28:49.000+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/etl_ex_bbva.py']
[2025-01-31T02:28:49.021+0000] {subprocess.py:99} INFO - Output:
[2025-01-31T02:28:54.312+0000] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-01-31T02:28:54.322+0000] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-01-31T02:28:54.336+0000] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-01-31T02:28:54.343+0000] {subprocess.py:106} INFO -              'port': '3306',
[2025-01-31T02:28:54.346+0000] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-01-31T02:28:54.448+0000] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-01-31T02:28:54.450+0000] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-01-31T02:28:54.452+0000] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-01-31T02:28:54.454+0000] {subprocess.py:106} INFO -              'port': '3306',
[2025-01-31T02:28:54.456+0000] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-01-31T02:28:54.852+0000] {subprocess.py:106} INFO - 2025-01-31 02:28:54,852 - assets - INFO - Engine para base de datos: calidad_etl creado exitosamente
[2025-01-31T02:28:54.866+0000] {subprocess.py:106} INFO - ic| fecha_inicio: datetime.date(2025, 1, 1)
[2025-01-31T02:28:54.868+0000] {subprocess.py:106} INFO -     fecha_fin: datetime.date(2025, 1, 31)
[2025-01-31T02:29:12.367+0000] {subprocess.py:106} INFO - 2025-01-31 02:29:12,366 - assets - INFO - SQL query succesfully executed
[2025-01-31T02:33:06.756+0000] {subprocess.py:106} INFO - 2025-01-31 02:33:06,755 - etl_ex_bbva - INFO - Reporte como_vamos.xlsx successfully load
[2025-01-31T02:33:07.220+0000] {subprocess.py:106} INFO - ic| dataset.ID_ATENCION_ONYX: 9    IM3009381
[2025-01-31T02:33:07.222+0000] {subprocess.py:106} INFO -                               Name: ID_ATENCION_ONYX, dtype: object
[2025-01-31T02:33:07.223+0000] {subprocess.py:106} INFO - 2025-01-31 02:33:07,220 - etl_ex_bbva - INFO - etl_ex_bbva.py success execution
[2025-01-31T02:33:07.255+0000] {subprocess.py:106} INFO - Conexi√≥n exitosa a la base de datos: calidad_etl
[2025-01-31T02:33:08.005+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-31T02:33:08.062+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T02:33:08.064+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=etl_ex_bbva, run_id=manual__2025-01-31T02:28:45.809531+00:00, execution_date=20250131T022845, start_date=20250131T022848, end_date=20250131T023308
[2025-01-31T02:33:08.131+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T02:33:08.171+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-31T02:33:08.178+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
