[2025-02-09T06:31:37.555-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T06:31:37.577-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva scheduled__2025-02-08T11:30:00+00:00 [queued]>
[2025-02-09T06:31:37.590-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva scheduled__2025-02-08T11:30:00+00:00 [queued]>
[2025-02-09T06:31:37.591-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-02-09T06:31:37.610-0500] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): etl_ex_bbva> on 2025-02-08 11:30:00+00:00
[2025-02-09T06:31:37.617-0500] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=71694) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-09T06:31:37.621-0500] {standard_task_runner.py:72} INFO - Started process 71696 to run task
[2025-02-09T06:31:37.620-0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'etl_ex_bbva', 'scheduled__2025-02-08T11:30:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmpc7rc83qx']
[2025-02-09T06:31:37.622-0500] {standard_task_runner.py:105} INFO - Job 85: Subtask etl_ex_bbva
[2025-02-09T06:31:37.699-0500] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.etl_ex_bbva scheduled__2025-02-08T11:30:00+00:00 [running]> on host 21f1c1b48730
[2025-02-09T06:31:37.852-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='etl_ex_bbva' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-08T11:30:00+00:00'
[2025-02-09T06:31:37.854-0500] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T06:31:37.882-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-09T06:31:37.884-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/etl_ex_bbva.py']
[2025-02-09T06:31:37.896-0500] {subprocess.py:99} INFO - Output:
[2025-02-09T06:31:40.772-0500] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-02-09T06:31:40.773-0500] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-02-09T06:31:40.774-0500] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-02-09T06:31:40.775-0500] {subprocess.py:106} INFO -              'port': '3306',
[2025-02-09T06:31:40.775-0500] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-02-09T06:31:40.808-0500] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-02-09T06:31:40.809-0500] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-02-09T06:31:40.810-0500] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-02-09T06:31:40.810-0500] {subprocess.py:106} INFO -              'port': '3306',
[2025-02-09T06:31:40.811-0500] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-02-09T06:31:41.475-0500] {subprocess.py:106} INFO - 2025-02-09 06:31:41,474 - assets - INFO - Engine para base de datos: calidad_etl creado exitosamente
[2025-02-09T06:31:41.479-0500] {subprocess.py:106} INFO - ic| hoy: datetime.date(2025, 2, 9)
[2025-02-09T06:31:41.479-0500] {subprocess.py:106} INFO -     fecha_inicio: datetime.date(2025, 2, 1)
[2025-02-09T06:31:41.483-0500] {subprocess.py:106} INFO - ic| fecha_inicio: datetime.date(2025, 2, 1)
[2025-02-09T06:31:41.483-0500] {subprocess.py:106} INFO -     fecha_fin: datetime.date(2025, 2, 9)
[2025-02-09T06:31:41.487-0500] {subprocess.py:106} INFO - ic| query: '
[2025-02-09T06:31:41.487-0500] {subprocess.py:106} INFO -             SELECT * FROM calidad_etl.sm_cerrado
[2025-02-09T06:31:41.488-0500] {subprocess.py:106} INFO -                 WHERE "INSERTAR_DT" >= %s;
[2025-02-09T06:31:41.489-0500] {subprocess.py:106} INFO -             '
[2025-02-09T06:31:41.784-0500] {subprocess.py:106} INFO - 2025-02-09 06:31:41,783 - assets - INFO - SQL query succesfully executed
[2025-02-09T06:31:41.785-0500] {subprocess.py:106} INFO - 2025-02-09 06:31:41,784 - etl_ex_bbva - INFO - Start ETL Exito Tuya BBVA
[2025-02-09T06:31:44.511-0500] {subprocess.py:106} INFO - 2025-02-09 06:31:44,511 - etl_ex_bbva - INFO - Reporte como_vamos.xlsx successfully load
[2025-02-09T06:31:44.670-0500] {subprocess.py:106} INFO - 2025-02-09 06:31:44,670 - etl_ex_bbva - INFO - etl_ex_bbva.py success execution
[2025-02-09T06:31:44.671-0500] {subprocess.py:106} INFO - Conexi√≥n exitosa a la base de datos: calidad_etl
[2025-02-09T06:31:44.974-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-09T06:31:45.007-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T06:31:45.009-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=etl_ex_bbva, run_id=scheduled__2025-02-08T11:30:00+00:00, execution_date=20250208T113000, start_date=20250209T113137, end_date=20250209T113145
[2025-02-09T06:31:45.030-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-09T06:31:45.059-0500] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-09T06:31:45.063-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
