[2025-02-11T06:30:00.897-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T06:30:00.917-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos scheduled__2025-02-10T11:30:00+00:00 [queued]>
[2025-02-11T06:30:00.927-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos scheduled__2025-02-10T11:30:00+00:00 [queued]>
[2025-02-11T06:30:00.929-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-02-11T06:30:00.946-0500] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task_bot_como_vamos> on 2025-02-10 11:30:00+00:00
[2025-02-11T06:30:00.952-0500] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=7624) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T06:30:00.954-0500] {standard_task_runner.py:72} INFO - Started process 7625 to run task
[2025-02-11T06:30:00.954-0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'task_bot_como_vamos', 'scheduled__2025-02-10T11:30:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmpit92jdxp']
[2025-02-11T06:30:00.956-0500] {standard_task_runner.py:105} INFO - Job 94: Subtask task_bot_como_vamos
[2025-02-11T06:30:01.007-0500] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos scheduled__2025-02-10T11:30:00+00:00 [running]> on host 21f1c1b48730
[2025-02-11T06:30:01.117-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='task_bot_como_vamos' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-10T11:30:00+00:00'
[2025-02-11T06:30:01.119-0500] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T06:30:01.139-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-11T06:30:01.141-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/bot_reporte_como_vamos.py']
[2025-02-11T06:30:01.153-0500] {subprocess.py:99} INFO - Output:
[2025-02-11T06:30:04.187-0500] {subprocess.py:106} INFO - ic| report_date: '10/02/2025'
[2025-02-11T06:30:04.189-0500] {subprocess.py:106} INFO - 2025-02-11 06:30:04,187 - bot_como_vamos - INFO - Starting script bot_como_vamos.py
[2025-02-11T06:30:04.979-0500] {subprocess.py:106} INFO - 2025-02-11 06:30:04,979 - bot_como_vamos - INFO - Conexi√≥n al Selenium Hub establecida correctamente
[2025-02-11T06:31:01.918-0500] {subprocess.py:106} INFO - ic| login_success: <selenium.webdriver.remote.webelement.WebElement (session="c3bf0e61faa42c9221284fdcb16064d1", element="f.D279F966C96DA6404911C5BB248A0F2E.d.C11AF8B9A21E2FDFC661D42C0E4CD6C8.e.77")>
[2025-02-11T06:31:01.925-0500] {subprocess.py:106} INFO - 2025-02-11 06:31:01,916 - bot_como_vamos - INFO - Loging success
[2025-02-11T06:31:12.061-0500] {subprocess.py:106} INFO - 2025-02-11 06:31:12,061 - bot_como_vamos - INFO - Click in menu button successfully
[2025-02-11T06:31:22.266-0500] {subprocess.py:106} INFO - 2025-02-11 06:31:22,266 - bot_como_vamos - INFO - Input dates successfully
[2025-02-11T06:31:32.387-0500] {subprocess.py:106} INFO - 2025-02-11 06:31:32,386 - bot_como_vamos - INFO - Click in 'Empresas Y Negocios' successfully
[2025-02-11T06:32:06.474-0500] {subprocess.py:106} INFO - 2025-02-11 06:32:06,472 - assets - INFO - Waiting for download file...............
[2025-02-11T06:32:06.544-0500] {subprocess.py:106} INFO - ic| file: '.com.google.Chrome.9fdQ0R'
[2025-02-11T06:32:11.549-0500] {subprocess.py:106} INFO - ic| file: 'Reporte como_vamos.xlsx'
[2025-02-11T06:32:11.550-0500] {subprocess.py:106} INFO - 2025-02-11 06:32:11,549 - bot_como_vamos - INFO - Download Reporte como_vamos succesfully
[2025-02-11T06:32:12.248-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-11T06:32:12.342-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T06:32:12.344-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=task_bot_como_vamos, run_id=scheduled__2025-02-10T11:30:00+00:00, execution_date=20250210T113000, start_date=20250211T113000, end_date=20250211T113212
[2025-02-11T06:32:12.416-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T06:32:12.488-0500] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-02-11T06:32:12.492-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
