[2025-02-13T18:24:06.211-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T18:24:06.232-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos manual__2025-02-13T23:24:05.217618+00:00 [queued]>
[2025-02-13T18:24:06.241-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos manual__2025-02-13T23:24:05.217618+00:00 [queued]>
[2025-02-13T18:24:06.243-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-02-13T18:24:06.258-0500] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task_bot_como_vamos> on 2025-02-13 23:24:05.217618+00:00
[2025-02-13T18:24:06.265-0500] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=52201) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T18:24:06.266-0500] {standard_task_runner.py:72} INFO - Started process 52202 to run task
[2025-02-13T18:24:06.267-0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'task_bot_como_vamos', 'manual__2025-02-13T23:24:05.217618+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmpm2tohi4r']
[2025-02-13T18:24:06.268-0500] {standard_task_runner.py:105} INFO - Job 116: Subtask task_bot_como_vamos
[2025-02-13T18:24:06.329-0500] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos manual__2025-02-13T23:24:05.217618+00:00 [running]> on host 21f1c1b48730
[2025-02-13T18:24:06.444-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='task_bot_como_vamos' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T23:24:05.217618+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T23:24:05.217618+00:00'
[2025-02-13T18:24:06.446-0500] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-13T18:24:06.475-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-13T18:24:06.477-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/bot_reporte_como_vamos.py']
[2025-02-13T18:24:06.491-0500] {subprocess.py:99} INFO - Output:
[2025-02-13T18:24:09.565-0500] {subprocess.py:106} INFO - ic| report_date: '12/02/2025'
[2025-02-13T18:24:09.566-0500] {subprocess.py:106} INFO - 2025-02-13 18:24:09,565 - bot_como_vamos - INFO - Starting script bot_como_vamos.py
[2025-02-13T18:24:10.403-0500] {subprocess.py:106} INFO - 2025-02-13 18:24:10,403 - bot_como_vamos - INFO - Conexi√≥n al Selenium Hub establecida correctamente
[2025-02-13T18:24:50.515-0500] {subprocess.py:106} INFO - ic| login_success: <selenium.webdriver.remote.webelement.WebElement (session="8df53c30e8354158d50b971d1884e8e9", element="f.974F30FDE345FCF5532D4EC29053CFC1.d.CA95574CFD0B7EC563966FE27F1A84D4.e.77")>
[2025-02-13T18:24:50.516-0500] {subprocess.py:106} INFO - 2025-02-13 18:24:50,515 - bot_como_vamos - INFO - Loging success
[2025-02-13T18:25:00.640-0500] {subprocess.py:106} INFO - 2025-02-13 18:25:00,639 - bot_como_vamos - INFO - Click in menu button successfully
[2025-02-13T18:25:10.918-0500] {subprocess.py:106} INFO - 2025-02-13 18:25:10,918 - bot_como_vamos - INFO - Input dates successfully
[2025-02-13T18:25:21.057-0500] {subprocess.py:106} INFO - 2025-02-13 18:25:21,057 - bot_como_vamos - INFO - Click in 'Empresas Y Negocios' successfully
[2025-02-13T18:25:44.227-0500] {subprocess.py:106} INFO - 2025-02-13 18:25:44,227 - assets - INFO - Waiting for download file...............
[2025-02-13T18:25:44.291-0500] {subprocess.py:106} INFO - ic| file: '.com.google.Chrome.cROKvV'
[2025-02-13T18:25:44.294-0500] {subprocess.py:106} INFO - ic| file: 'Unconfirmed 418016.crdownload'
[2025-02-13T18:25:49.300-0500] {subprocess.py:106} INFO - ic| file: 'Reporte como_vamos.xlsx'
[2025-02-13T18:25:49.301-0500] {subprocess.py:106} INFO - 2025-02-13 18:25:49,300 - bot_como_vamos - INFO - Download Reporte como_vamos succesfully
[2025-02-13T18:25:49.614-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-13T18:25:49.647-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-13T18:25:49.648-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=task_bot_como_vamos, run_id=manual__2025-02-13T23:24:05.217618+00:00, execution_date=20250213T232405, start_date=20250213T232406, end_date=20250213T232549
[2025-02-13T18:25:49.695-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T18:25:49.719-0500] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T18:25:49.723-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
